name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: krdlab/setup-haxe@master
      - run: haxe --version
      - name: Checkout this repository
        uses: actions/checkout@main

      - run: haxe --run RunSetup
      - run: haxelib list

      - name: setting git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Count changes
        id: changes
        run: |
          git status -s -uall
          echo "::set-output name=count::$((git status -s -uall | Measure-Object).Count)"
      - name: commit
        run: |
          git status -s -uall
          echo "count: ${{ steps.changes.outputs.count }}"
          git remote -v
          git branch --show-current
          echo ----add----
          git add ./*.hxml
          echo ----commit----
          git commit -m "github-actions auto commit"
          echo ----push----
          git push
        if: steps.changes.outputs.count > 0
      - run: |
          git add -N .
          git diff --exit-code

